
"use client";

import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-3xl mx-auto">
      <PageHeader
        title="Privacy Policy"
        description="Our commitment to your privacy."
        actions={
          <Button variant="outline" asChild>
            <Link href="/"><ArrowLeft className="mr-2 h-4 w-4" /> Back to Home</Link>
          </Button>
        }
      />
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle>Vical Farmart Privacy Policy</CardTitle>
          <CardDescription>Last Updated: {new Date().toLocaleDateString()}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6 prose prose-sm sm:prose-base max-w-none">
          <p>
            ‘VICAL FARMART’ is a service provided by Agricultural Investment Consult (VICAL FARMS).
            The term ‘User’ refers to any person(s) visiting our website/ mobile Application
            “www.vicalfarmart.com / vical farmart mobile App”.
            This policy outlines how users of our service information’s are collected, used and protected.
          </p>

          <h2 className="text-xl font-semibold">How your information is use.</h2>
          <p>
            We only collect personal information from you when you order goods or services on our website, when 
            you complete any customer survey, or through cookies.
          </p>
          <p>
            We collect this information in order to enable orders, such as name, address, email address, phone 
            number, or payment information; using our Applications implies the User has agreed to the terms and 
            condition described in this Privacy Policy.
          </p>

          <h2 className="text-xl font-semibold">Cookies and Google Analytics</h2>
          <p>
            Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. 
            These are sent to your browser from the websites that you visit and are stored on your device&apos;s internal 
            memory.
          </p>
          <p>
            This Service does not use these “cookies” explicitly. However, the app may use third party code and 
            libraries that use “cookies” to collect information and improve their services.
          </p>
          <p>
            ‘’vical farmart app’’ does not uses Google Analytics, a web analytics service provided by Google, Inc.
            (&quot;Google&quot;). Google Analytics uses &quot;cookies&quot; (see above). The information generated by the cookie about 
            your use of the website will be transmitted to and stored by Google on servers in the United States.
          </p>
          <p>
            By using this website/ app, you consent to the processing of data about you by Google in the manner ad 
            for the purposes set out above. 
          </p>

          <h2 className="text-xl font-semibold">Service Providers</h2>
          <p>
            We may engage a third-party company to handle some aspects of our services such as shipping. Users 
            Personal Information shall not be disclose by the third party in event in performing his/ her task except 
            by the Law of the country of operation. However, any third party agent engage by us is obligated not to 
            disclose or use the information of USER for any other purpose.
          </p>

          <h2 className="text-xl font-semibold">Security</h2>
          <p>
            Protection of your Personal Information is what we strive for. However, no method of 
            transmission over the internet, or method of electronic storage is 100% secure and reliable, and 
            for such reason we may not guarantee its absolute security.
          </p>

          <h2 className="text-xl font-semibold">Children’s Privacy</h2>
          <p>
            These Services do not address anyone under the age of 13. We do not knowingly collect 
            personally identifiable information from children under 13. In the case we discover that a child 
            under 13 has provided me with personal information, we immediately delete this from our 
            servers. If you are a parent or guardian and you are aware that your child has provided us with 
            personal information, please contact us so that we will be able to do necessary actions.
          </p>

          <h2 className="text-xl font-semibold">Changes to This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. Thus, you are advised to review this page 
            periodically for any changes. we will notify you of any changes by posting the new Privacy Policy 
            on this page. These changes are effective immediately after they are posted on this page.
          </p>

          <h2 className="text-xl font-semibold">Contact Us</h2>
          <p>
            If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact us
            at info@vicalfarms.com.
          </p>
          <p>
            Tel: +233 302958685
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
